name: Cleanup and Deploy

on:
  push:
    branches:
      - main

jobs:
  cleanup-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run cleanup script
        run: |
          # Run your cleanup script here
          make build
      
      - name: Push changes to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Cleanup dev dependencies" || echo "No changes to commit"
          git remote add auth-origin https://github.com/la-strole/webhook.git
          git push auth-origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    